### ISSUE TITLE
Code for “Online code repository: Tensor and matrix low-rank value- function approximation in reinforcement learning”

### ISSUE THREAD

**Issue by bigekko** [sergiorozada12/low-rank-rl#3]
Hello, I am a graduate student from THU. I have read your article "Tensor and matrix low-rank value-function approximation in Reinforcement learning", which says that the code is provided. But I did not find it in the corresponding link. Could you please upload the code again? Thank you!

**Comment by sergiorozada12** [comment]
You could not see it because it was not public! Thanks for pointing out, because I haven't realized. Please, find the code in the following directory:

https://github.com/sergiorozada12/tensor-low-rank-rl

I'm currently doing a refactor of the code. Probably it will change (for the better) in the following months, in order to follow some better coding practices.
